/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package com.mycompany.donnasalone.view;

import com.mycompany.donnasalone.controll.ServiceController;

import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JButton;
import javax.swing.JComboBox;
import javax.swing.JOptionPane;
import javax.swing.JScrollPane;

import javax.swing.JTable;
import javax.swing.JTextPane;

/**
 *
 * @author jonas
 */
public final class ServiceView extends javax.swing.JFrame {
       private final AdminView view;
    private final ServiceController controller;
   
    

    /** Creates new form ServiceView */
    public ServiceView() {
        initComponents();
       
        this.getMsggg().setVisible(false);
        this.view = new AdminView();
        controller = new ServiceController(this);
        
        setLocationRelativeTo(null);
        
          try {
               this.controller.checked();
           } catch (SQLException ex) {
               Logger.getLogger(ServiceView.class.getName()).log(Level.SEVERE, null, ex);
           }
          
      
          
        
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
     
    @SuppressWarnings("unchecked")
    
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel1 = new javax.swing.JLabel();
        jButtonservice = new javax.swing.JButton();
        msggg = new javax.swing.JScrollPane();
        jTextPanepppp = new javax.swing.JTextPane();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTDados = new javax.swing.JTable();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jButtonEndereco = new javax.swing.JButton();
        jComboBox1 = new javax.swing.JComboBox<>();
        jComboBox2 = new javax.swing.JComboBox<>();
        jButtonDesc = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jButtonClient = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocation(new java.awt.Point(0, 0));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 88, 276, 10));

        jLabel1.setFont(new java.awt.Font("DejaVu Sans", 1, 24)); // NOI18N
        jLabel1.setText("Consulta____.");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(31, 41, -1, -1));

        jButtonservice.setBackground(new java.awt.Color(255, 255, 255));
        jButtonservice.setFont(new java.awt.Font("Fira Sans Semi-Light", 0, 14)); // NOI18N
        jButtonservice.setForeground(new java.awt.Color(0, 0, 0));
        jButtonservice.setText("add Serviço");
        jButtonservice.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonserviceActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonservice, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 210, 140, -1));

        jTextPanepppp.setFont(new java.awt.Font("FreeSerif", 2, 24)); // NOI18N
        jTextPanepppp.setForeground(new java.awt.Color(63, 96, 108));
        msggg.setViewportView(jTextPanepppp);

        jPanel1.add(msggg, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 260, 570, 100));

        jTDados.setBackground(new java.awt.Color(0, 0, 0));
        jTDados.setFont(new java.awt.Font("Fira Sans Semi-Light", 1, 13)); // NOI18N
        jTDados.setForeground(new java.awt.Color(99, 177, 188));
        jTDados.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jTDados.setToolTipText("");
        jTDados.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jTDados.setGridColor(new java.awt.Color(255, 248, 248));
        jTDados.setName(""); // NOI18N
        jTDados.setOpaque(false);
        jTDados.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jTDados.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jTDados.setShowGrid(true);
        jScrollPane1.setViewportView(jTDados);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 110, 690, 270));

        jButton2.setBackground(new java.awt.Color(255, 255, 255));
        jButton2.setFont(new java.awt.Font("Fira Sans Semi-Light", 0, 14)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setIcon(new javax.swing.ImageIcon("/home/jonas/NetBeansProjects/donnaSalone/src/main/java/com/mycompany/donnasalone/img/lup")); // NOI18N
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 40, 100, 60));

        jButton3.setBackground(new java.awt.Color(255, 255, 255));
        jButton3.setFont(new java.awt.Font("Fira Sans Semi-Light", 0, 14)); // NOI18N
        jButton3.setForeground(new java.awt.Color(0, 0, 0));
        jButton3.setText("Limpar");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 370, 140, -1));

        jLabel2.setFont(new java.awt.Font("Fira Sans Semi-Light", 1, 13)); // NOI18N
        jLabel2.setText("Buscar:");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 70, -1, -1));
        jPanel1.add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 60, 230, -1));

        jButtonEndereco.setBackground(new java.awt.Color(255, 255, 255));
        jButtonEndereco.setFont(new java.awt.Font("Fira Sans Semi-Light", 0, 14)); // NOI18N
        jButtonEndereco.setForeground(new java.awt.Color(0, 0, 0));
        jButtonEndereco.setText("add Endereço");
        jButtonEndereco.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEnderecoActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonEndereco, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 290, 140, -1));

        jComboBox1.setBackground(new java.awt.Color(255, 255, 255));
        jComboBox1.setFont(new java.awt.Font("Fira Sans Semi-Light", 1, 14)); // NOI18N
        jComboBox1.setForeground(new java.awt.Color(15, 114, 241));
        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Serviço", "Cliente", "Endereço" }));
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });
        jPanel1.add(jComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 100, 180, -1));

        jComboBox2.setBackground(new java.awt.Color(255, 255, 255));
        jComboBox2.setFont(new java.awt.Font("Fira Sans Semi-Light", 1, 14)); // NOI18N
        jComboBox2.setEnabled(false);
        jComboBox2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox2ActionPerformed(evt);
            }
        });
        jPanel1.add(jComboBox2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 150, 180, -1));

        jButtonDesc.setBackground(new java.awt.Color(255, 255, 255));
        jButtonDesc.setFont(new java.awt.Font("Fira Sans Semi-Light", 0, 14)); // NOI18N
        jButtonDesc.setForeground(new java.awt.Color(0, 0, 0));
        jButtonDesc.setText("Descrição");
        jButtonDesc.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jButtonDescMouseDragged(evt);
            }
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                jButtonDescMouseMoved(evt);
            }
        });
        jButtonDesc.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jButtonDescMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jButtonDescMouseExited(evt);
            }
        });
        jButtonDesc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonDescActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonDesc, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 330, 140, -1));

        jButton1.setBackground(new java.awt.Color(255, 255, 255));
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setIcon(new javax.swing.ImageIcon("/home/jonas/NetBeansProjects/donnaSalone/src/main/java/com/mycompany/donnasalone/img/lixo")); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 40, 60, 60));

        jButtonClient.setBackground(new java.awt.Color(255, 255, 255));
        jButtonClient.setFont(new java.awt.Font("Fira Sans Semi-Light", 0, 14)); // NOI18N
        jButtonClient.setForeground(new java.awt.Color(0, 0, 0));
        jButtonClient.setText("add Cliente");
        jButtonClient.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonClientActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonClient, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 250, 140, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 908, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 414, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
       
        
    }//GEN-LAST:event_formWindowClosed

    
    private void jButtonEnderecoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEnderecoActionPerformed
        this.setVisible(false);
        new AddressView().setVisible(true);
      
      
    }//GEN-LAST:event_jButtonEnderecoActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
  try {
               this.controller.checked();
           } catch (SQLException ex) {
               Logger.getLogger(ServiceView.class.getName()).log(Level.SEVERE, null, ex);
           }      
        
        
    }//GEN-LAST:event_jComboBox1ActionPerformed

    public JTable getjTDados() {
        return jTDados;
    }

    public void setjTDados(JTable jTDados) {
        this.jTDados = jTDados;
    }

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
          controller.limpar();
        
    }//GEN-LAST:event_jButton3ActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        
        try {
               controller.combobox();
           } catch (SQLException ex) {
               Logger.getLogger(ServiceView.class.getName()).log(Level.SEVERE, null, ex);
           }
         
    }//GEN-LAST:event_formWindowOpened

    private void jComboBox2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox2ActionPerformed
           try {
               controller.comboboxEvent();
           } catch (SQLException ex) {
               Logger.getLogger(ServiceView.class.getName()).log(Level.SEVERE, null, ex);
           }
        
        
    }//GEN-LAST:event_jComboBox2ActionPerformed

    private void jButtonserviceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonserviceActionPerformed
       
         new RegisterServiceView().setVisible(true);
          this.setVisible(false);
        
    }//GEN-LAST:event_jButtonserviceActionPerformed

    private void jButtonDescActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonDescActionPerformed
        
    }//GEN-LAST:event_jButtonDescActionPerformed

    private void jButtonDescMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonDescMouseMoved
       
        
    }//GEN-LAST:event_jButtonDescMouseMoved

    private void jButtonDescMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonDescMouseDragged
        
    }//GEN-LAST:event_jButtonDescMouseDragged

    private void jButtonDescMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonDescMouseEntered
        controller.desc();
        
    }//GEN-LAST:event_jButtonDescMouseEntered

    private void jButtonDescMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonDescMouseExited
       controller.out();
    }//GEN-LAST:event_jButtonDescMouseExited

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        controller.del();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButtonClientActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonClientActionPerformed
          new RegisterView().setVisible(true);
          this.setVisible(false);        
    }//GEN-LAST:event_jButtonClientActionPerformed

    public JComboBox<String> getjComboBox1() {
        return jComboBox1;
    }

    public void setjComboBox1(JComboBox<String> jComboBox1) {
        this.jComboBox1 = jComboBox1;
    }

    public JComboBox<Object> getjComboBox2() {
        return jComboBox2;
    }

    public void setjComboBox2(JComboBox<Object> jComboBox2) {
        this.jComboBox2 = jComboBox2;
    }

    public JTextPane getjTextPanepppp() {
        return jTextPanepppp;
    }

    public void setjTextPanepppp(JTextPane jTextPanepppp) {
        this.jTextPanepppp = jTextPanepppp;
    }

    public JScrollPane getMsggg() {
        return msggg;
    }

    public void setMsggg(JScrollPane msggg) {
        this.msggg = msggg;
    }

    public JButton getjButtonClient() {
        return jButtonClient;
    }

    public void setjButtonClient(JButton jButtonClient) {
        this.jButtonClient = jButtonClient;
    }

   

    public JButton getjButtonservice() {
        return jButtonservice;
    }

    public void setjButtonservice(JButton jButtonservice) {
        this.jButtonservice = jButtonservice;
    }

    public JButton getjButtonDesc() {
        return jButtonDesc;
    }

    public void setjButtonDesc(JButton jButtonDesc) {
        this.jButtonDesc = jButtonDesc;
    }

    public JButton getjButtonEndereco() {
        return jButtonEndereco;
    }

    public void setjButtonEndereco(JButton jButtonEndereco) {
        this.jButtonEndereco = jButtonEndereco;
    }

 
   




   
  

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ServiceView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ServiceView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ServiceView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ServiceView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ServiceView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButtonClient;
    private javax.swing.JButton jButtonDesc;
    private javax.swing.JButton jButtonEndereco;
    private javax.swing.JButton jButtonservice;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JComboBox<Object> jComboBox2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTable jTDados;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextPane jTextPanepppp;
    private javax.swing.JScrollPane msggg;
    // End of variables declaration//GEN-END:variables

    public void showSms(String sms) {
        JOptionPane.showMessageDialog(null, sms);
    }

}
